import { FaAws, FaJava } from "react-icons/fa";
import {
  SiNodedotjs,
  SiExpress,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiFirebase,
  SiReact,
  SiJavascript,
  SiPython,
  SiHtml5,
  SiCss3,
  SiDocker,
  SiNextdotjs,
  SiTypescript,
} from "react-icons/si";

export const tagIconMap = {
  HTML: SiHtml5,
  CSS: SiCss3,
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  React: SiReact,
  "Next.js": SiNextdotjs,
  "Node.js": SiNodedotjs,
  Node: SiNodedotjs,
  Express: SiExpress,
  "Express.js": SiExpress,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  MongoDB: SiMongodb,
  Firebase: SiFirebase,
  Python: SiPython,
  Docker: SiDocker,
  AWS: FaAws,
  Java: FaJava,
};

export const tagColorMap = {
  HTML: "#E34F26",
  CSS: "#1572B6",
  JavaScript: "#F7DF1E",
  TypeScript: "#3178C6",
  React: "#61DAFB",
  "Next.js": "#FFFFFF",
  "Node.js": "#339933",
  Node: "#339933",
  Express: "#FFFFFF",
  "Express.js": "#FFFFFF",
  PostgreSQL: "#336791",
  MySQL: "#4479A1",
  MongoDB: "#47A248",
  Firebase: "#FFCA28",
  Python: "#3776AB",
  Docker: "#2496ED",
  AWS: "#FF9900",
  Java: "#007396",
};
